@echo off
echo [rebuild] Tearing down containers, images, and volumes...
docker compose down --rmi all --volumes
echo [rebuild] Building and starting services...
docker compose up --build --detach --remove-orphans
echo [rebuild] Pruning unused volumes...
docker volume prune -f
echo [rebuild] Pruning unused images...
docker image prune -f -a
echo [rebuild] Done.
